# -*- coding: utf-8 -*-
"""
@author:yangxb23
@github:https://github.com/xuebin-yang/
@data:02/12/2021
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui_1 file 'final_version.ui_1'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QIcon
import qtawesome
from time import sleep
import sys
from PyQt5.QtCore import QObject, pyqtSignal, QEventLoop, QTimer, QThread, QTime
from PyQt5.QtGui import QTextCursor


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")   # 主窗口
        MainWindow.setFixedSize(900, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QGridLayout()   # 设置主窗口布局
        self.centralwidget.setLayout(self.main_layout)   # 给主窗口加布局
        self.widget = QtWidgets.QWidget()  # 左侧窗口
        self.widget.setObjectName("左侧窗口")
        self.widget1 = QtWidgets.QWidget()  # 右侧布局
        self.widget1.setObjectName("右侧布局")
        self.main_layout.addWidget(self.widget, 0, 0, 12, 2)  # 左侧窗口在第0行第0列
        self.main_layout.addWidget(self.widget1, 0, 2, 12, 10)  # 右侧部件在第0行第3列，占13行9列

        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)   # 设置左侧窗口的布局
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("左边布局")
        self.widget.setLayout(self.gridLayout_4)

        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget1)  # 右侧布局
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget1.setLayout(self.gridLayout_5)

        self.pushButton = QtWidgets.QPushButton("")  # 最大化
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton.setFixedSize(15, 15)

        self.pushButton_2 = QtWidgets.QPushButton("")  # 最小化
        self.pushButton_2.setObjectName("pushButton_2")

        self.gridLayout_4.addWidget(self.pushButton_2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pushButton_2.setFixedSize(15, 15)

        self.pushButton_3 = QtWidgets.QPushButton("")  # 关闭
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_3.setFixedSize(15, 15)

        self.pushButton.setStyleSheet('''QPushButton{background:#F76677;border-radius:5px;}QPushButton:hover{background:red;}''')
        self.pushButton_2.setStyleSheet('''QPushButton{background:#F7D674;border-radius:5px;}QPushButton:hover{background:yellow;}''')
        self.pushButton_3.setStyleSheet('''QPushButton{background:#6DDF6D;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_13 = QtWidgets.QPushButton(qtawesome.icon('fa.gear', color='yellow'), "图像识别")   # 系统功能
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.setStyleSheet(
            '''QPushButton{
                border:none;
                color:yellow;
                font-size:20px;
                height:40px;
                padding-left:3px;
                text-align:center;
            }
            QPushButton:hover{         
                color:black;         
                border:1px solid #F3F3E5;         
                border-radius:15px;         
                background:#F3ffe3;     
            }
            '''
        )
        self.gridLayout_4.addWidget(self.pushButton_13, 1, 1, 1, 1)

        self.pushButton_14 = QtWidgets.QPushButton(qtawesome.icon('fa.trophy', color='yellow'), "对比结果")   # 图像识别
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.setStyleSheet(
            '''QPushButton{
                border:none;
                color:yellow;
                font-size:20px;
                height:40px;
                padding-left:3px;
                text-align:center;
            }
            QPushButton:hover{         
                color:black;         
                border:1px solid #F3F3E5;         
                border-radius:15px;         
                background:#F3ffe3;     
            }
            '''
        )
        self.gridLayout_4.addWidget(self.pushButton_14, 2, 1, 1, 1)

        # self.pushButton_15 = QtWidgets.QPushButton(qtawesome.icon('fa.music', color='white'), "对比结果")   # 对比分析
        # self.pushButton_15.setObjectName("pushButton_15")
        # self.gridLayout_4.addWidget(self.pushButton_15, 3, 1, 1, 1)

        self.qlable = QtWidgets.QLabel("")
        self.qlable.setObjectName("占位标签")
        self.gridLayout_4.addWidget(self.qlable, 6, 1, 1, 1)

        self.widget.setStyleSheet(
            '''QPushButton{         
                border:none;         
                color:black;         
                font-size:18px;         
                height:40px;         
                padding-left:5px;         
                padding-right:15px;         
                text-align:left;     
            }     
            QPushButton:hover{         
                color:black;         
                border:1px solid #F3F3F5;         
                border-radius:15px;         
                background:LightGray;     
            }
            #MainWindow{background-color:#ffffff; color:red;}
            '''
        )

        self.stackedWidget = QtWidgets.QStackedWidget(self.widget1)  # 右侧窗口设置成栈窗口
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()    # 第一个页面
        self.page.setObjectName("the first page")

        self.layoutWidget = QtWidgets.QWidget(self.page)   # 对比分析，第一个页面的布局
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 680, 657))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)   # 第一个页面里面是格点布局
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5.addWidget(self.page, 0, 3, 12, 8)

        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget)   # ACC5 按键
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(108, 40))
        self.pushButton_12.setStyleSheet("font: 14pt \"楷体\";\n"
"background-color: rgb(98, 170, 127);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 3, 2, 1, 2)

        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget)   # 数据集选择
        self.pushButton_7.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_7.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_7.setStyleSheet("font: 14pt \"楷体\";\n"
"background-color: rgb(255,150, 17);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 0, 1, 1)

        self.label_5 = QtWidgets.QLabel(self.layoutWidget)    # 推理日志信息框
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 6)
        self.label_5.setStyleSheet("""
            QLabel{
                font-family: "Microsoft YaHei";  
                font-size: 13px;   
                color: #FF8B45;    
                font-style: Americian;   
                font-weight: bold;   
            }
        """
        )

        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget)   # aircraft
        self.radioButton_3.setMaximumSize(QtCore.QSize(130, 16777215))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_3.setStyleSheet("""
            QRadioButton{
                font-family: "Microsoft YaHei";  
                font-size: 20px;   
                color: #FF8B45;    
                font-style: Americian;   
                font-weight: bold;   
            }
            QRadioButton:hover{
                color: #6495ED;
                background-color: none;
            }
            QRadioButton:pressed{
                color: green;
                border-color: green;
                background-color: #B0C4DE;
            }
            QRadioButton::indicator { 
                width: 25px;
                height: 25px;
            }
            QRadioButton:indicator:unchecked{
                image: url(./ui/unchecked.png)
            }
            QRadioButton:indicator:checked{
                image: url(./ui/checked.png)
            }
        """
        )
        self.gridLayout.addWidget(self.radioButton_3, 0, 5, 1, 1)

        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget)    # 耗时
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(88, 40))
        self.pushButton_9.setStyleSheet("font: 14pt \"楷体\";\n"
"background-color: rgb(85, 170, 127);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 2)

        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget)   # 耗时
        self.lineEdit_11.setMinimumSize(QtCore.QSize(128, 40))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_11.setStyleSheet("font: 15pt \"楷体\";color: rgb(255, 0, 0);")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_11.setStyleSheet(
            '''QLineEdit{
                border:none;
                color:black;
                font-size:20px;
                height:40px;
                text-align:center;
                background-color:rgb(255, 255, 255);
            }
            '''
        )
        self.gridLayout.addWidget(self.lineEdit_11, 2, 4, 1, 2)

        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget)  # acc1
        self.lineEdit_9.setMinimumSize(QtCore.QSize(128, 40))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_9.setStyleSheet("font: 15pt \"楷体\";color: rgb(255, 0, 0);")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_9.setStyleSheet(
            '''QLineEdit{
                border:none;
                color:black;
                font-size:20px;
                height:40px;
                padding-left:5px;
                text-align:center;
                background-color:rgb(255, 255, 255);
            }
            '''
        )
        self.gridLayout.addWidget(self.lineEdit_9, 3, 1, 1, 1)

        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)   # 数据集 stanford car
        self.radioButton_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.setStyleSheet("""
                    QRadioButton{
                        font-family: "Microsoft YaHei";  
                        font-size: 20px;   
                        color: #FF8B45;    
                        font-style: Americian;   
                        font-weight: bold;   
                    }
                    QRadioButton:hover{
                        color: #6495ED;
                        background-color: none;
                    }
                    QRadioButton:pressed{
                        color: green;
                        border-color: green;
                        background-color: #B0C4DE;
                    }
                    QRadioButton::indicator { 
                        width: 25px;
                        height: 25px;
                    }
                    QRadioButton:indicator:unchecked{
                        image: url(./ui/unchecked.png)
                    }
                    QRadioButton:indicator:checked{
                        image: url(./ui/checked.png)
                    }
                """
                                         )
        self.gridLayout.addWidget(self.radioButton_2, 0, 2, 1, 1)

        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget)   # 图像分辨率
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(108, 40))
        self.pushButton_11.setStyleSheet("font: 14pt \"楷体\";\n"
"background-color: rgb(98, 170, 127);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 2, 0, 1, 1)

        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)   # 数据集 CUB200
        self.radioButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.radioButton.setObjectName("radioButton")
        self.radioButton.setStyleSheet("""
                    QRadioButton{
                        font-family: "Microsoft YaHei";  
                        font-size: 20px;   
                        color: #FF8B45;    
                        font-style: Americian;   
                        font-weight: bold;   
                    }
                    QRadioButton:hover{
                        color: #6495ED;
                        background-color: none;
                    }
                    QRadioButton:pressed{
                        color: green;
                        border-color: green;
                        background-color: #B0C4DE;
                    }
                    QRadioButton::indicator { 
                        width: 25px;
                        height: 25px;
                    }
                    QRadioButton:indicator:unchecked{
                        image: url(./ui/unchecked.png)
                    }
                    QRadioButton:indicator:checked{
                        image: url(./ui/checked.png)
                    }
                """
        )
        self.gridLayout.addWidget(self.radioButton, 0, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget)   # acc5
        self.lineEdit_10.setMinimumSize(QtCore.QSize(128, 40))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_10.setStyleSheet("font: 15pt \"楷体\";color: rgb(255, 0, 0);")
        self.lineEdit_10.setText("")
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_10.setStyleSheet(
            '''QLineEdit{
                border:none;
                color:black;
                font-size:20px;
                height:40px;
                padding-left:5px;
                text-align:center;
                background-color:rgb(255, 255, 255);
            }
            '''
        )
        self.gridLayout.addWidget(self.lineEdit_10, 3, 4, 1, 2)

        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget)   # 开始推理
        self.pushButton_10.setMinimumSize(QtCore.QSize(472, 0))
        self.pushButton_10.setStyleSheet("font: 14pt \"楷体\";\n"
"background-color: rgb(150, 169, 27);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 0, 1, 6)
        self.pushButton_10.setStyleSheet(
            '''QPushButton{
                border:none;
                color:black;
                font-size:20px;
                height:40px;
                padding-left:5px;
                text-align:center;
                background-color:rgb(150, 169, 27);
            }
            QPushButton:hover{         
                color:black;         
                border:1px solid #F3F3F5;         
                border-radius:15px;         
                background:green;     
            }
            '''
        )

        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)   # 推理日志信息
        self.textBrowser.setMinimumSize(QtCore.QSize(420, 361))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(0)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("font: 10pt \"楷体\";\n"
"background-color: rgb(240, 250, 250);")
        self.textBrowser.setLineWidth(2)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 4, 0, 1, 6)

        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget)   # 显示图像分辨率
        self.lineEdit_8.setMinimumSize(QtCore.QSize(128, 40))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_8.setStyleSheet("font: 15pt \"楷体\";color: rgb(255, 0, 0);")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_8.setStyleSheet(
            '''QLineEdit{
                border:none;
                color:black;
                font-size:20px;
                height:40px;
                padding-left:5px;
                text-align:center;
                background-color:rgb(255, 255, 255);
            }
            '''
        )
        self.gridLayout.addWidget(self.lineEdit_8, 2, 1, 1, 1)

        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget)   # acc1
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(108, 40))
        self.pushButton_8.setStyleSheet("font: 14pt \"楷体\";\n"
"background-color: rgb(98, 170, 127);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)

        self.page_2 = QtWidgets.QWidget()   # 第二页   对应图像识别界面
        self.page_2.setObjectName("page_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 20, 680, 657))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_5.setStyleSheet("font: 14pt \"楷体\";\n"
"background-color: rgb(255,150, 17);")
        self.pushButton_5.setMinimumSize(100, 40)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)

        # 可选框
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_4.setStyleSheet("""
                    QRadioButton{
                        font-family: "Microsoft YaHei";  
                        font-size: 20px;   
                        color: #FF8B45;    
                        font-style: Americian;   
                        font-weight: bold;   
                    }
                    QRadioButton:hover{
                        color: #F00B45;
                        background-color: none;
                    }
                    QRadioButton:pressed{
                        color: green;
                        border-color: green;
                        background-color: #B0C4DE;
                    }
                    QRadioButton::indicator { 
                        width: 25px;
                        height: 25px;
                    }
                    QRadioButton:indicator:unchecked{
                        image: url(./ui/unchecked.png)
                    }
                    QRadioButton:indicator:checked{
                        image: url(./ui/checked.png)
                    }
                """
                                         )
        self.horizontalLayout_2.addWidget(self.radioButton_4, 1)

        self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_5.setStyleSheet("""
                    QRadioButton{
                        font-family: "Microsoft YaHei";  
                        font-size: 20px;   
                        color: #FF8B45;    
                        font-style: Americian;   
                        font-weight: bold;   
                    }
                    QRadioButton:hover{
                        color: #F00B45;
                        background-color: none;
                    }
                    QRadioButton:pressed{
                        color: green;
                        border-color: green;
                        background-color: #B0C4DE;
                    }
                    QRadioButton::indicator { 
                        width: 25px;
                        height: 25px;
                    }
                    QRadioButton:indicator:unchecked{
                        image: url(./ui/unchecked.png)
                    }
                    QRadioButton:indicator:checked{
                        image: url(./ui/checked.png)
                    }
                """
        )
        self.horizontalLayout_2.addWidget(self.radioButton_5, 1)

        self.radioButton_6 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_6.setStyleSheet("""
                    QRadioButton{
                        font-family: "Microsoft YaHei";  
                        font-size: 20px;   
                        color: #FF8B45;    
                        font-style: Americian;   
                        font-weight: bold;   
                    }
                    QRadioButton:hover{
                        color: #F00B45;
                        background-color: none;
                    }
                    QRadioButton:pressed{
                        color: green;
                        border-color: green;
                        background-color: #B0C4DE;
                    }
                    QRadioButton::indicator { 
                        width: 25px;
                        height: 25px;
                    }
                    QRadioButton:indicator:unchecked{
                        image: url(./ui/unchecked.png)
                    }
                    QRadioButton:indicator:checked{
                        image: url(./ui/checked.png)
                    }
                """
                                         )
        self.horizontalLayout_2.addWidget(self.radioButton_6, 1)

        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_4.setStyleSheet("font: 14pt \"楷体\";\n"
"background-color: rgb(150, 169, 27);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_4.setStyleSheet(
            '''QPushButton{
                border:none;
                color:black;
                font-size:20px;
                height:40px;
                padding-left:5px;
                padding-right:15px;
                text-align:center;
                background-color:rgb(150, 169, 27);
            }
            QPushButton:hover{         
                color:black;         
                border:1px solid #F3F3F5;         
                border-radius:15px;         
                background:green;     
            }
            '''
        )
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_6.setStyleSheet("font: 14pt \"楷体\";\n"
"background-color: rgb(150, 169, 27);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_6.setStyleSheet(
            '''QPushButton{
                border:none;
                color:black;
                font-size:20px;
                height:40px;
                padding-left:5px;
                padding-right:15px;
                text-align:center;
                background-color:rgb(150, 169, 27);
            }
            QPushButton:hover{         
                color:black;         
                border:1px solid #F3F3F5;         
                border-radius:15px;         
                background:green;     
            }
            '''
        )
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        # self.textBrowser_1 = QtWidgets.QTextBrowser(self.layoutWidget_2)
        self.ListWidget = QtWidgets.QListWidget(self.layoutWidget_2)  # 图像路径
        self.ListWidget.setMinimumSize(QtCore.QSize(224, 200))
        self.ListWidget.setLineWidth(0)
        self.ListWidget.setObjectName("QListWidget")

        self.verticalLayout_3.addWidget(self.ListWidget)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet("""
                    QLabel{
                        font-family: "Microsoft YaHei";  
                        font-size: 13px;   
                        color: #F888E5;    
                        font-style: Americian;   
                        font-weight: bold;   
                    }
                """
        )

        self.verticalLayout_3.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setMinimumSize(QtCore.QSize(100, 40))
        self.label_6.setMaximumSize(QtCore.QSize(110, 40))
        self.label_6.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setLineWidth(2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)

        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget_2)  # 预测类别
        self.lineEdit_7.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit_7.setStyleSheet("font: 15pt \"楷体\";color: rgb(255, 0, 0);")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_7.setStyleSheet(
            '''QLineEdit{
                border:none;
                color:black;
                font-size:20px;
                height:40px;
                padding-left:5px;
                padding-right:15px;
                text-align:center;
                background-color:rgb(255, 255, 255);
            }
            '''
        )
        self.gridLayout_3.addWidget(self.lineEdit_7, 0, 1, 1, 1)

        self.label_12 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_12.setMinimumSize(QtCore.QSize(100, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_12.setStyleSheet("color: rgb(255, 0, 255);")
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setLineWidth(2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)

        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget_2)  # 真实类别
        self.lineEdit_12.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit_12.setStyleSheet("font: 15pt \"楷体\";color: rgb(255, 0, 0);")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_12.setStyleSheet(
            '''QLineEdit{
                border:none;
                color:black;
                font-size:20px;
                height:40px;
                padding-left:5px;
                padding-right:15px;
                text-align:center;
                background-color:rgb(255， 255， 255);
            }
            '''
        )

        self.gridLayout_3.addWidget(self.lineEdit_12, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)   # label_13 是预测对错
        self.label_13.setMinimumSize(QtCore.QSize(100, 0))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_13.setStyleSheet("color: rgb(255, 170, 127);")
        self.label_13.setFrameShape(QtWidgets.QFrame.Box)
        self.label_13.setLineWidth(2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)

        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget_2)   # 预测对错
        self.lineEdit_13.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit_13.setStyleSheet("font: 15pt \"楷体\";color: rgb(255, 0, 0);")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_13.setStyleSheet(
            '''QLineEdit{
                border:none;
                color:black;
                font-size:20px;
                height:40px;
                padding-left:5px;
                padding-right:15px;
                text-align:center;
                background-color:rgb(255, 255, 255);
            }
            '''
        )
        self.gridLayout_3.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 2, 1, 1, 1)

        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)    # label_2 显示原始图像
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)

        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(224, 224))
        self.label_13.setMaximumSize(QtCore.QSize(448, 448))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setLineWidth(2)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet(
            '''QLabel{
                border:none;
                color:white;
                font-size:20px;
                height:40px;
                text-align:center;
                background-color:rgb(255, 255, 255);
            }
            '''
        )
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_7.setStyleSheet("""
            QLabel{
                font-family: "Microsoft YaHei";  
                font-size: 13px;   
                color: #F888E5;    
                font-style: Americian;   
                font-weight: bold;   
            }
        """
        )
        self.gridLayout_2.addLayout(self.verticalLayout_2, 3, 0, 1, 1)

        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(224, 224))
        self.label_3.setMaximumSize(QtCore.QSize(448, 448))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setLineWidth(2)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3.setStyleSheet(
            '''QLabel{
                border:none;
                color:white;
                font-size:20px;
                height:40px;
                text-align:center;
                background-color:rgb(255, 255, 255);
            }
            '''
        )

        self.verticalLayout_4.addWidget(self.label_3)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_9.setStyleSheet("""
            QLabel{
                font-family: "Microsoft YaHei";  
                font-size: 13px;   
                color: #F888E5;    
                font-style: Americian;   
                font-weight: bold;   
            }
                        """
                                   )

        self.gridLayout_2.addLayout(self.verticalLayout_4, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_5.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.widget1.setStyleSheet(
            '''QPushButton{
                border:none;
                color:black;
                font-size:15px;
                height:40px;
                padding-left:5px;
                padding-right:15px;
                text-align:center;
            }'''
        )

        self.pushButton_14.clicked.connect(self.switchs)
        self.pushButton_13.clicked.connect(self.switchs)

        self.pushButton_6.clicked.connect(MainWindow.show_img)
        self.pushButton_4.clicked.connect(MainWindow.select_image)

        self.pushButton_10.clicked.connect(MainWindow.dataset_reference)

    def switchs(self):  # 根据id 切换页面
        dic = {"pushButton_14": 0, "pushButton_13": 1}
        index = dic[str(self.sender().objectName())]
        self.stackedWidget.setCurrentIndex(index)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", ""))
        self.pushButton_2.setText(_translate("MainWindow", ""))
        self.pushButton_3.setText(_translate("MainWindow", ""))
        self.pushButton_13.setText(_translate("MainWindow", "图像识别"))
        self.pushButton_14.setText(_translate("MainWindow", "对比结果"))
        # self.pushButton_15.setText(_translate("MainWindow", "对比结果"))
        self.pushButton_12.setText(_translate("MainWindow", "Top-5(%)"))
        self.pushButton_7.setText(_translate("MainWindow", "功能选择"))
        self.label_5.setText(_translate("MainWindow", "打印控制台输出信息"))
        self.radioButton_3.setText(_translate("MainWindow", "飞机识别"))   # 对比分析
        self.pushButton_9.setText(_translate("MainWindow", "推理耗时(s)"))
        self.radioButton_2.setText(_translate("MainWindow", "车型识别"))  #
        self.pushButton_11.setText(_translate("MainWindow", "推理分辨率"))
        self.radioButton.setText(_translate("MainWindow", "鸟类识别"))   #
        self.pushButton_10.setText(_translate("MainWindow", "运行推理"))
        self.pushButton_8.setText(_translate("MainWindow", "Top-1(%)"))
        self.pushButton_5.setText(_translate("MainWindow", "功能选择"))
        self.radioButton_4.setText(_translate("MainWindow", "鸟类识别"))   # 图像识别
        self.radioButton_5.setText(_translate("MainWindow", "车型识别"))
        self.radioButton_6.setText(_translate("MainWindow", "飞机识别"))
        self.pushButton_4.setText(_translate("MainWindow", "上传图像"))
        self.pushButton_6.setText(_translate("MainWindow", "开始识别"))
        self.label_4.setText(_translate("MainWindow", "KNN(K=20)检索结果"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">预测类别</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">类别概率</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">预测时间</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "原始图像"))
        self.label_9.setText(_translate("MainWindow", "模型 ROI"))

    def printf(self, mes):
        self.textBrowser.append(mes)  # 在指定的区域显示提示信息
        self.cursot = self.textBrowser.textCursor()
        self.textBrowser.moveCursor(self.cursot.End)
        sleep(1)
        QtWidgets.QApplication.processEvents()


